steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'REGION-docker.pkg.dev/$PROJECT_ID/repo/backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'REGION-docker.pkg.dev/$PROJECT_ID/repo/backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - secure-doc-backend
      - --image=REGION-docker.pkg.dev/$PROJECT_ID/repo/backend
      - --region=asia-southeast2
      - --platform=managed
      - --allow-unauthenticated
